# Generated by Django 3.0.2 on 2020-02-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200223_1423'),
        ('users', '0002_auto_20200216_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_posts',
            field=models.ManyToManyField(related_name='liked_by', to='blog.Post'),
        ),
    ]
