# Generated by Django 3.0.2 on 2020-02-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200223_1434'),
        ('users', '0003_profile_liked_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='liked_posts',
            field=models.ManyToManyField(related_name='liked_profile', to='blog.Post'),
        ),
    ]
